### ISSUE TITLE
Improve the scheme configuration form

### ISSUE THREAD

**Issue by agentrickard** [palantirnet/workbench_access#108]
Looking at the form now, we have a bit of an issue in that, for Taxonomy at least, the Vocabulary selection is independent of the field selection.

It is possible to select no vocabularies -- making access permissions for users and role un-configurable -- and yet still assign a field for access control.

I see a few possible solutions:

* Validate that the fields include the selected vocabulary on submit -- easiest solution
* Hide / deselect fields that do not include the selected vocabulary -- likely requires AJAX.
* Derive scheme options from the assigned fields directly -- which seems complex.

Open to other ideas.

**Comment by larowlan** [comment]
Vote 1 for validation in the plugin, each plugin can do that in its validateConfigurationForm method
