### ISSUE TITLE
Views handling for all sections?

### ISSUE THREAD

**Issue by agentrickard** [palantirnet/workbench_access#109]
Currently, the Views handlers only apply to one access scheme at a time.

That is probably fine, because I think it would be rare for a site to use multiple schemes on the same content type. It is, however, possible.

When viewing users in particular, we might like the option to display _all_ section assignments. This feature would require an additional Views handler.

**Comment by larowlan** [comment]
Although, people could add the same field twice, and use views existing functionality to join multiple fields together? Wouldn't work for filtering obviously.

**Comment by agentrickard** [comment]
Right now, the Section Association view filter will display all sections, so perhaps that's enough for now.
