### ISSUE TITLE
Try extending to all content entities

### ISSUE THREAD

**Issue by agentrickard** [palantirnet/workbench_access#25]
Explore how to make this apply to any fieldable content entity.

**Comment by acbramley** [comment]
Any more thought on this one? Would be great to be able to use the module with custom entity types.

**Comment by agentrickard** [comment]
Do we have an equivalent hook or event to hook_node_access() that applies to all/other entity types?

If so, this should be fairly obvious code to implement.

**Comment by agentrickard** [comment]
So I should have looked first. We have hook_entity_access() which makes this feature fairly clear:

* Move hook_node_access() and hook_node_create_access() code to hook_entity_access() and hook_entty_create_access().
* Move the current configuration to separate parts: 
  * Scheme assignment should (I think) be global to avoid confusion and moved to its own tab
  * Make the field settings entity-type specific, starting with Node, with tabs for other Content Entity types.
  * Ideally, move user storage to its own custom entity
* Update form_alter() code to react to any assigned entity
* Update the views_data_alter() code to react to any assigned entity
* Consider removing node module as a dependency
* Perhaps change how configuration is managed, as right now we use a third-party setting on the node type. This would be more easily managed if it were centralized to Workbench Access.

Questions:

* Should we allow different schemes for different entities? I don't think so, because then we'd have to store user sections per entity type, which seems like a recipe for confusion.

* Should node and taxonomy modules be required?

* How do we handle cases where the assigned scheme doesn't apply to certain entity types? I'm specifically thinking of the Menu handler here. Can all entity types be added to a menu? Is that our problem?

**Comment by larowlan** [comment]
Sounds like a good plan to me.

In terms of the questions

1) If we move user storage to custom entity, that would be easier. But I think one scheme per site would do. Go for the 80% use case.
2) No
3) I think we would need to have handlers like workbench moderation `$entityTypeManager->getDefinition('node')->getHandler('workbench_access')->schemeIsCompatible($schemeId)` kind of thing

**Comment by acbramley** [comment]
@agentrickard @larowlan yeah the hooks are the easy part to fix up I think it's all the other smaller bits that will be harder. Does this depend on #66 being resolved first?

**Comment by agentrickard** [comment]
I don't think #66 is a hard requirement. For some reason I think this conversion is easier than that one.

However, consistent storage is a goal.

Perhaps the best approach would be the following:

* Finish the necessary tasks to release 8.x-1.0 stable
* Start an 8.x-2.0 branch that alters the storage and introduces more entity types.

**Comment by agentrickard** [comment]
@larowlan I keep trying to ask you if you think #66 is a blocker to this work.

**Comment by larowlan** [comment]
timezones--
No I don't think it is a blocker

**Comment by larowlan** [comment]
Having a stab at this

**Comment by larowlan** [comment]
Making some good progress

**Comment by agentrickard** [comment]
I'm happy to look at code.

**Comment by larowlan** [comment]
See #83
