### ISSUE TITLE
Exporting config breaks subsequent site installs

### ISSUE THREAD

**Issue by patrickfweston** [palantirnet/workbench_access#39]
After installing and configuring workbench access, I exported configuration with `drush cex`. The site functions properly. If I re-run a site install, the configuration does not properly import and the site install fails. 

Specifically, I receive the following error message: 

```
(I'll find it and post it)
```

Adding a try/catch around workbench_access_confirm_fields() in workbench_access.module() allows the build to finish properly.

**Comment by agentrickard** [comment]
I added this yesterday.

https://github.com/agentrickard/workbench_access/commit/87219539dbf24f549a4e9b771f6f09ae04ac760e
