### ISSUE TITLE
ID undefined

### ISSUE THREAD

**Issue by patrickfweston** [palantirnet/workbench_access#42]
An error is thrown when trying to edit a node when logged in as a user that has been assigned to a section. 

```
Undefined property: Drupal\Core\Session\AccountProxy::$id in Drupal\workbench_access\AccessControlHierarchyBase->checkEntityAccess()
```

**Potential Fix**
In AccessControlHierarchyBase.php on line 199:

```
$user_sections = $manager->getUserSections($account->id);
```

there is a call to grab the property id from $account. This property does not exist. Instead, the method id() should be called:

```
$user_sections = $manager->getUserSections($account->id());
```

**Comment by agentrickard** [comment]
Fixed.
