### ISSUE TITLE
Role based access ignored

### ISSUE THREAD

**Issue by patrickfweston** [palantirnet/workbench_access#43]
In WorkbenchAccessManager.php, line 132 should be changed from:

```
$user_sections += $this->getRoleSections($user);
```

to

```
$user_sections = array_merge($user_sections, $this->getRoleSections($user));
```

Because the arrays being added share keys, the keys from the left hand side are used and the right hand side are ignored:

"The + operator returns the right-hand array appended to the left-hand array; for keys that exist in both arrays, the elements from the left-hand array will be used, and the matching elements from the right-hand array will be ignored."

from: http://php.net/manual/en/language.operators.array.php

**Comment by agentrickard** [comment]
Sigh.
