### ISSUE TITLE
Apply to the create operation

### ISSUE THREAD

**Issue by agentrickard** [palantirnet/workbench_access#58]
hook_node_access no longer works on Create, use hook_node_create_access.

Users not assigned to a section cannot create content of types controlled by WA.

**Comment by larowlan** [comment]
I can work on this today

**Comment by larowlan** [comment]
Not sure how this would work?

```php
public function createAccess($entity_bundle = NULL, AccountInterface $account = NULL, array $context = array(), $return_as_object = FALSE);
```

At that stage there is no entity, so no section we can check against.

**Comment by larowlan** [comment]
I think instead we need to write a `ValidationConstraint` that limits the options they can select for the content's editorial section when the entity is new.

**Comment by agentrickard** [comment]
The only check we need to run is this:

* Is this bundle governed by Workbench Access?
* Is the user assigned to at least one section?

We have code for this check in AccessControlHierarchyBase::checkEntityAccess()

```
      // Discover the field and check status.
      $entity_sections = $this->getEntityValues($entity, $field);
      // If no value is set on the entity, ignore.
      // @TODO: Is this the correct logic? It is helpful for new installs.
      if (empty($entity_sections)) {
        $return = AccessResult::neutral();
      }
```

The issue is simply that the 'create' op is no longer passed through hook_node_access.

**Comment by agentrickard** [comment]
Speaking of `ValidationConstraint`, that's implemented, but probably in the wrong way. We currently handle that at the form display level, using workbench_access_form_node_form_alter() and the methods invoked by it.

We don't currently validate on submit, we just restrict on form generation. The issue here is "If the form field would be empty, deny create action entirely."
