### ISSUE TITLE
Vacation / sabbatical plan

### ISSUE THREAD

**Issue by agentrickard** [palantirnet/workbench_access#70]
Hey active devs! I'll be at DrupalCON Baltimore next week and then officially out on sabbatical for the month of May.

During that time, I'll be on vacation for at least two weeks without a computer.

My plan is to give @larowlan commit access to this repo, and let him sync code between GitHub and Drupal,org as a co-maintainer.

@acbramley any concerns?

**Comment by jibran** [comment]
Thanks, that would be awesome.

**Comment by agentrickard** [comment]
Thanks. On a side note: I will be at the DrupalCON sprints on Friday next week, if anyone wants to collaborate in person.

**Comment by acbramley** [comment]
Sounds great Ken, enjoy your trip!

**Comment by larowlan** [comment]
Thanks, enjoy your trip Ken.

**Comment by agentrickard** [comment]
Invite sent.
