### ISSUE TITLE
Move the user field to a base field now that core supports purging base fields

### ISSUE THREAD

**Issue by larowlan** [palantirnet/workbench_access#84]
Core now supports purging base fields - https://www.drupal.org/node/2907780

So the field_workbench_access field on the user entity could be a base field

## Advantages

- gets rid of all the code to create the configurable one
- stops people deleting it

## Disadvantages

- If we implement #66 we don't need it and would need to remove it anyway

**Comment by jibran** [comment]
I think we should implement #66 then.
