### ISSUE TITLE
Get rid of the drush commands

### ISSUE THREAD

**Issue by larowlan** [palantirnet/workbench_access#86]
If #83 goes in, the drush commands to 'set stuff up' and 'flush' can probably go.

The flush is replaced by 'deleting' a scheme, which flushes for you.

We could instead ship an example module, like other modules do - e.g. webform.

The test module does just that, it has config for both a menu and a taxonomy setup, with views.

**Comment by agentrickard** [comment]
I have been using the test configuration command every time in install the module for development. 

Testing whether enabling workbench_access_test provides the same feature.

**Comment by agentrickard** [comment]
Hm, well, you can't enable hidden modules....

I really like having the shorthand to be able to install a test vocabulary and configuration. What other options do we have?

**Comment by larowlan** [comment]
You can if you add this to your settings.php

```php
$settings['extension_discovery_scan_tests'] = TRUE;
```

But we could make it an example module instead of a test module, with some minor refactoring

**Comment by agentrickard** [comment]
Changing settings is good enough, if it works.
